# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
stages:
- stage: Build
  displayName: Build

  jobs:
    - job: InstallJmeter
      displayName: Install Jmeter Tool
      pool:
        vmImage: ubuntu-latest
  


      steps:
      - task: JMeterInstaller@0
        inputs:
          jmeterVersion: 5.2.1
  
      - task: Bash@3
        displayName: Run Jmeter Sample Test
        inputs:
          targetType: inline
          script: jmeter -n -t automatedtesting/jmeter/Starter_1.jmx -Jresdir=automatedtesting/jmeter/end_test.csv -l automatedtesting/jmeter/report/Starter_results.jtl -e -o automatedtesting/jmeter/Starter

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: automatedtesting/jmeter
          ArtifactName: jmeter
          publishLocation: Container
